name: SonarCloud Analysis

on:
    push:
        branches:
            - main
            - develop
    pull_request:

jobs:
    sonar:
        name: SonarCloud Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Instalar dependências
              run: npm install

            - name: Rodar análise do SonarCloud
              uses: SonarSource/SonarCloud-scan-action@v2
              with:
                  args: >
                      -Dsonar.organization=Daniel Loureiro Cintra
                      -Dsonar.projectKey=tech-lead-quality-lab
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
